/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Compra.java
 *
 * Created on 19/11/2010, 17:36:10
 */

package gui;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import persistencia.PersistenciaEstoque;

import estoque.Compra;
import estoque.Item;
import estoque.ItemCompra;
import estoque.ItemPedido;
import gui.*;

/**
 *
 * @author walkiria
 */
public class FrameMovimentoCompra extends javax.swing.JFrame {
	private Principal principal;
	private Compra compra; 

    /** Creates new form Compra */
    public FrameMovimentoCompra(Principal principal,Compra compra) {
		initComponents();
		this.principal = principal;
		if(compra == null ){
			JOptionPane.showConfirmDialog(null,"OOps","mensagem",JOptionPane.CLOSED_OPTION);
		}
		this.compra = compra;
		this.labelFornecedor.setText(compra.getNomeFornecedor());
		this.labelData.setText(compra.getDataCompra(null));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        compraTextFieldCodigo = new javax.swing.JTextField();
        compraTextFieldQuantidade = new javax.swing.JTextField();
        compraTextFieldPreco = new javax.swing.JTextField();
        compraJlabelCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        compraLabelPreco = new javax.swing.JLabel();
        compraJlabelQtdTotal = new javax.swing.JLabel();
        compraJlabelPrecoTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelPreco = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        labelFornecedor = new javax.swing.JLabel();
        RealizarCompra = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        botaoAdiconar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        compraJlabelFornecedor = new javax.swing.JLabel();
        compraJlabelQuantidade = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        compraJlabelFornecedor1 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        compraTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraTextFieldCodigoActionPerformed(evt);
            }
        });

        compraTextFieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraTextFieldQuantidadeActionPerformed(evt);
            }
        });

        compraTextFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraTextFieldPrecoActionPerformed(evt);
            }
        });

        compraJlabelCodigo.setText("Código");

        compraLabelPreco.setText("Preço R$");

        compraJlabelQtdTotal.setText("Quantidade Itens:");

        compraJlabelPrecoTotal.setText("Preço total R$");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RealizarCompra.setText("Editar ou Adicionar:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            		"linha","Código","Nome", "Preço", "Quantidade", "subTotal"
            }
        ));
        jTable3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(jTable3);

        botaoAdiconar.setText("Adicionar");
        botaoAdiconar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdiconarActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar Campos");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        compraJlabelFornecedor.setText("Fornecedor:");

        compraJlabelQuantidade.setText("Quantidade");

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar Alteração");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        compraJlabelFornecedor1.setText("Data:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compraJlabelPrecoTotal)
                            .addComponent(compraJlabelQtdTotal))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(compraJlabelFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(compraJlabelFornecedor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RealizarCompra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(compraJlabelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compraTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compraJlabelQuantidade)
                                .addGap(18, 18, 18)
                                .addComponent(compraTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRemover)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(compraLabelPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(compraTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoAdiconar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compraJlabelFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compraJlabelFornecedor1)
                            .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compraJlabelPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compraJlabelQtdTotal)
                            .addComponent(labelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RealizarCompra)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(compraTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(compraJlabelCodigo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(compraLabelPreco)
                        .addComponent(compraTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(compraJlabelQuantidade)
                        .addComponent(compraTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoRemover)
                            .addComponent(botaoEditar)
                            .addComponent(botaoSalvar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoAdiconar)
                            .addComponent(botaoLimpar)
                            .addComponent(botaoSair))))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void botaoAdiconarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdiconarActionPerformed
		Integer codigo = 0,quant = 0;
		Float preco = (float)0.0;
		String nome;
		Item item = null;
		
		if(compraTextFieldCodigo.getText() == null || compraTextFieldCodigo.getText().length() == 0){
			mensagem("O campo Código não pode estar em branco");
			return;
		}
		else{
			try{
				codigo = Integer.parseInt(compraTextFieldCodigo.getText());
				item = PersistenciaEstoque.getInstance().searchItem(codigo);
			}
			catch (NumberFormatException e) {
				nome = compraTextFieldCodigo.getText();
				item = PersistenciaEstoque.getInstance().searchItem(nome);
			}
		}
		if(compraTextFieldPreco.getText() == null || compraTextFieldPreco.getText().length() == 0){
			mensagem("O campo Preço não pode estar em branco");
			return;
		}
		else{
			try{
				preco = Float.parseFloat(compraTextFieldPreco.getText());
				if(preco <= 0 ){
					mensagem("Preço deve ser maior que zero");
					return;
				}
			}
			catch (NumberFormatException e) {
				mensagem("O campo Preço não é um valor válido");
				return;
			}
		}
		if(compraTextFieldQuantidade.getText() == null || compraTextFieldQuantidade.getText().length() == 0){
			mensagem("O campo Quantidade não pode estar em branco");
			return;
		}
		else{
			try{
				quant = Integer.parseInt(compraTextFieldQuantidade.getText());
				if(quant <= 0 ){
					mensagem("Quantidade deve ser maior que zero");
					return;
				}
			}
			catch (NumberFormatException e) {
				mensagem("O campo quantidade não é um valor válido");
				return;
			}
		}
		if (item == null ){
			mensagem("Item não encontrado");
			return;
		}
		else{
			if(compra.addItem(item, preco, quant)){
				jTable3.setModel(getData());
				limpaCampos();
			}
			else{
				mensagem("oops!nao adicionei");
			}
		}

	}//GEN-LAST:event_botaoAdiconarActionPerformed

	private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
		limpaCampos();
	}//GEN-LAST:event_botaoLimparActionPerformed

	private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
	    this.principal.setEnabled(true);
		this.dispose();
	}//GEN-LAST:event_botaoSairActionPerformed

	private void compraTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraTextFieldCodigoActionPerformed
		compraTextFieldCodigo.setText("");
	}//GEN-LAST:event_compraTextFieldCodigoActionPerformed

	private void compraTextFieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraTextFieldQuantidadeActionPerformed
		compraTextFieldQuantidade.setText("");
	}//GEN-LAST:event_compraTextFieldQuantidadeActionPerformed

	private void compraTextFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraTextFieldPrecoActionPerformed
		compraTextFieldPreco.setText("");// TODO add your handling code here:
	}//GEN-LAST:event_compraTextFieldPrecoActionPerformed

	private void jTable3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable3AncestorAdded
		// TODO add your handling code here:
	}//GEN-LAST:event_jTable3AncestorAdded

	private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
		int selecionado = jTable3.getSelectedRow();
		if(selecionado >= 0) {
			compra.removeLinha(selecionado);
			jTable3.setModel(getData());
			}
		else{
			mensagem("nenhuma linha selecionada");
			return;
		}
	}//GEN-LAST:event_botaoRemoverActionPerformed

	private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_botaoEditarActionPerformed

	private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_botaoSalvarActionPerformed
	
	private TableModel getData(){
		ArrayList<ItemCompra> itens = compra.overview();
		Vector<Vector<String>> dados = new Vector<Vector<String>>();
		Vector<String> headers = new Vector<String>();
		String [] headersName = new String[]{"linha","Código","Nome","Preço", "Quantidade", "subTotal"};
		int linha=0;
		Float total = (float) 0.0,subtotal = (float) 0.0;
		for (int i = 0; i < headersName.length; i++) {
			headers.add(headersName[i]);
		}
		if (itens != null){
			for (ItemCompra itensC : itens) {
		    	subtotal = itensC.getPrecoCompra() * itensC.getQuant();
				Vector<String> vetor = new Vector<String>();
				vetor.add(((Integer)linha).toString());
				vetor.add(((Integer)itensC.getCodigoItem()).toString());
				vetor.add(itensC.getNomeItem());
				vetor.add(((Float)itensC.getPrecoCompra()).toString());
				vetor.add(((Integer)itensC.getQuant()).toString());
				vetor.add(subtotal.toString());
				total+=subtotal;
				dados.add(linha,vetor);
				linha++;
			}
		}
		else{
			DefaultTableModel model = new DefaultTableModel(new String[][]{}, headersName);
			labelPreco.setText("0.00");
			labelQuantidade.setText("0");
			return model;			
		}
		DefaultTableModel model = new DefaultTableModel(dados, headers);
		labelPreco.setText(total.toString());
		labelQuantidade.setText(((Integer)dados.size()).toString());
		return model;
 	}

	private void limpaCampos() {
		compraTextFieldPreco.setText("");
		compraTextFieldQuantidade.setText("");
		compraTextFieldCodigo.setText(" ");
	}
	
	private void mensagem(String mensagem) {
		JOptionPane.showConfirmDialog(null,mensagem,"mensagem",JOptionPane.CLOSED_OPTION);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RealizarCompra;
    private javax.swing.JButton botaoAdiconar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel compraJlabelCodigo;
    private javax.swing.JLabel compraJlabelFornecedor;
    private javax.swing.JLabel compraJlabelFornecedor1;
    private javax.swing.JLabel compraJlabelPrecoTotal;
    private javax.swing.JLabel compraJlabelQtdTotal;
    private javax.swing.JLabel compraJlabelQuantidade;
    private javax.swing.JLabel compraLabelPreco;
    private javax.swing.JTextField compraTextFieldCodigo;
    private javax.swing.JTextField compraTextFieldPreco;
    private javax.swing.JTextField compraTextFieldQuantidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    // End of variables declaration//GEN-END:variables

}
