/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal2.java
 *
 * Created on 23/11/2010, 17:08:36
 */

package javaapplication4;

/**
 *
 * @author isac
 */
public class Principal2 extends javax.swing.JFrame {

    /** Creates new form Principal2 */
    public Principal2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuConsultaFornecedor = new javax.swing.JMenuItem();
        menuConsultaClientes = new javax.swing.JMenuItem();
        menuConsultaUsuários = new javax.swing.JMenuItem();
        menuConsultaItens = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCadastroFornecedores = new javax.swing.JMenuItem();
        menuCadastroClientes = new javax.swing.JMenuItem();
        menuCadastroItens = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuIniciarCompra = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuIniciarVenda = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuAdicionarUsuarios = new javax.swing.JMenuItem();
        menuRemoverUsuários = new javax.swing.JMenuItem();
        menuAlterarSenha = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/isac/workspace/tp1-POO/src/gui/logo.png")); // NOI18N

        jLabel2.setText("Insira Nome de Usuário e senha:");

        botaoOk.setText("Ok");

        botaoCancelar.setText("Cancelar");

        labelNome.setText("Nome:");

        labelSenha.setText("Senha:");

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addGap(18, 18, 18)
                .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSenha)
                .addGap(18, 18, 18)
                .addComponent(campoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(botaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCancelar)
                .addGap(28, 28, 28))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaoCancelar))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        menuLogin.setText("Login");
        jMenu1.add(menuLogin);

        menuLogout.setText("Logout");
        jMenu1.add(menuLogout);

        menuSair.setText("Sair");
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        menuConsultaFornecedor.setText("Fornecedores");
        jMenu2.add(menuConsultaFornecedor);

        menuConsultaClientes.setText("Clientes");
        jMenu2.add(menuConsultaClientes);

        menuConsultaUsuários.setText("Usuários");
        jMenu2.add(menuConsultaUsuários);

        menuConsultaItens.setText("Itens");
        jMenu2.add(menuConsultaItens);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cadastros");

        menuCadastroFornecedores.setText("Fornecedores");
        jMenu3.add(menuCadastroFornecedores);

        menuCadastroClientes.setText("Clientes");
        jMenu3.add(menuCadastroClientes);

        menuCadastroItens.setText("Itens");
        jMenu3.add(menuCadastroItens);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Compra");

        menuIniciarCompra.setText("Iniciar Compra");
        jMenu4.add(menuIniciarCompra);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Venda");

        menuIniciarVenda.setText("Iniciar Venda");
        jMenu5.add(menuIniciarVenda);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Usuários");

        menuAdicionarUsuarios.setText("Adicionar");
        jMenu6.add(menuAdicionarUsuarios);

        menuRemoverUsuários.setText("Remover");
        jMenu6.add(menuRemoverUsuários);

        menuAlterarSenha.setText("Alterar Senha");
        jMenu6.add(menuAlterarSenha);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JMenuItem menuAdicionarUsuarios;
    private javax.swing.JMenuItem menuAlterarSenha;
    private javax.swing.JMenuItem menuCadastroClientes;
    private javax.swing.JMenuItem menuCadastroFornecedores;
    private javax.swing.JMenuItem menuCadastroItens;
    private javax.swing.JMenuItem menuConsultaClientes;
    private javax.swing.JMenuItem menuConsultaFornecedor;
    private javax.swing.JMenuItem menuConsultaItens;
    private javax.swing.JMenuItem menuConsultaUsuários;
    private javax.swing.JMenuItem menuIniciarCompra;
    private javax.swing.JMenuItem menuIniciarVenda;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuRemoverUsuários;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JPanel painelLogin;
    // End of variables declaration//GEN-END:variables

}
