/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 23/11/2010, 17:08:36
 */

package gui;

import javax.swing.JOptionPane;

import exceptions.PasswordsDontMatchException;
import exceptions.UserNotFoundException;

import persistencia.AccessControl;
import persistencia.Log;

/**
 *
 * @author isac
 */
public class Principal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Principal */
    public Principal() {
		try {
			javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch(Exception e) {
			e.printStackTrace();
		}
        initComponents();
        menuAlterarSenha.setEnabled(false);
        menuCadastroClientes.setEnabled(false);
        menuCadastroFornecedores.setEnabled(false);
        menuCadastroItens.setEnabled(false);
        menuConsultaClientes.setEnabled(true);
        menuConsultaFornecedor.setEnabled(true);
        menuConsultaItens.setEnabled(true);
        menuCadastroUsuarios.setEnabled(false);
        menuIniciarCompra.setEnabled(false);
        menuIniciarVenda.setEnabled(false);
        menuLogin.setEnabled(true);
        menuLogout.setEnabled(true);
        menuRemoverUsuários.setEnabled(false);
        menuSair.setEnabled(true);
        painelLogin.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuConsultaFornecedor = new javax.swing.JMenuItem();
        menuConsultaClientes = new javax.swing.JMenuItem();
        menuConsultaItens = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCadastroFornecedores = new javax.swing.JMenuItem();
        menuCadastroClientes = new javax.swing.JMenuItem();
        menuCadastroItens = new javax.swing.JMenuItem();
        menuCadastroUsuarios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuIniciarCompra = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuIniciarVenda = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuRemoverUsuários = new javax.swing.JMenuItem();
        menuAlterarSenha = new javax.swing.JMenuItem();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/logo.png"))); // NOI18N

        jLabel2.setText("Insira Nome de Usuário e senha:");

        botaoOk.setText("Ok");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        labelSenha.setText("Senha:");

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addGap(18, 18, 18)
                .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSenha)
                .addGap(18, 18, 18)
                .addComponent(campoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(botaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCancelar)
                .addGap(28, 28, 28))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaoCancelar))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogin);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        menuConsultaFornecedor.setText("Fornecedores");
        menuConsultaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultaFornecedor);

        menuConsultaClientes.setText("Clientes");
        menuConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaClientesActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultaClientes);

        menuConsultaItens.setText("Itens");
        menuConsultaItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaItensActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsultaItens);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cadastros");

        menuCadastroFornecedores.setText("Fornecedores");
        menuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadastroFornecedores);

        menuCadastroClientes.setText("Clientes");
        menuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClientesActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadastroClientes);

        menuCadastroItens.setText("Itens");
        menuCadastroItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroItensActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadastroItens);

        menuCadastroUsuarios.setText("Usuarios");
        menuCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadastroUsuarios);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Compra");

        menuIniciarCompra.setText("Iniciar Compra");
        menuIniciarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarCompraActionPerformed(evt);
            }
        });
        jMenu4.add(menuIniciarCompra);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Venda");

        menuIniciarVenda.setText("Iniciar Venda");
        menuIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarVendaActionPerformed(evt);
            }
        });
        jMenu5.add(menuIniciarVenda);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Usuários");

        menuRemoverUsuários.setText("Remover");
        menuRemoverUsuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoverUsuáriosActionPerformed(evt);
            }
        });
        jMenu6.add(menuRemoverUsuários);

        menuAlterarSenha.setText("Alterar Senha");
        menuAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarSenhaActionPerformed(evt);
            }
        });
        jMenu6.add(menuAlterarSenha);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
		login();
	}//GEN-LAST:event_botaoOkActionPerformed

	private void login() {
		if(campoNome.getText().length() == 0){
			mensagem("O campo nome não pode estar em branco");
			return;
		}
		else{
			try {
				if(AccessControl.login(campoNome.getText(),new String(campoSenha.getPassword()))){
					switch(AccessControl.getPermission(campoNome.getText())){
					case 1:{
						administrador();
						break;
						}
					case 2:{
						cliente();
						break;
					}
					case 3:{
						Fornecedor();
						break;
					}
					default:{
						painelLogin.setVisible(false);
					}
					
				}
				}
			} catch (UserNotFoundException e) {
				mensagem("Usuario nao encontrado");
				return;
			} catch (PasswordsDontMatchException e) {
				mensagem("Password errado");
				return;
			}
		}
	}

	private void Fornecedor() {
		menuAlterarSenha.setEnabled(true);
		menuCadastroItens.setEnabled(true);
		menuIniciarCompra.setEnabled(true);
		menuCadastroFornecedores.setEnabled(true);
		painelLogin.setVisible(false);
	}

	private void cliente() {
		menuAlterarSenha.setEnabled(true);
		menuIniciarVenda.setEnabled(true);
		menuCadastroClientes.setEnabled(true);
		painelLogin.setVisible(false);
	}

	private void administrador() {
		menuAlterarSenha.setEnabled(true);
		menuCadastroClientes.setEnabled(true);
		menuCadastroFornecedores.setEnabled(true);
		menuCadastroItens.setEnabled(true);
		menuCadastroUsuarios.setEnabled(true);
		menuIniciarCompra.setEnabled(true);
		menuIniciarVenda.setEnabled(true);
		menuRemoverUsuários.setEnabled(true);
		painelLogin.setVisible(false);
	}

	private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
		painelLogin.setVisible(false);
	}//GEN-LAST:event_botaoCancelarActionPerformed

	private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
		painelLogin.setVisible(true);
	}//GEN-LAST:event_menuLoginActionPerformed

	private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
		Log.getLoginstance(null).info("Usuário "+AccessControl.nome+" deslogado com sucesso");
		AccessControl.nome = "";
	}//GEN-LAST:event_menuLogoutActionPerformed

	private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
		this.dispose();
	}//GEN-LAST:event_menuSairActionPerformed

	private void menuConsultaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaFornecedorActionPerformed
		ConsultaFornecedor consultaFornecedor = new ConsultaFornecedor(this);
		consultaFornecedor.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuConsultaFornecedorActionPerformed

	private void menuConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaClientesActionPerformed
		ConsultaCliente consultaCliente = new ConsultaCliente(this);
		consultaCliente.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuConsultaClientesActionPerformed

	private void menuConsultaItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaItensActionPerformed
		ConsultaItem consultaItem = new ConsultaItem(this);
		consultaItem.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuConsultaItensActionPerformed

	private void menuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFornecedoresActionPerformed
		FrameCadastroFornecedor cadastroFornecedores = new FrameCadastroFornecedor(this);
		cadastroFornecedores.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuCadastroFornecedoresActionPerformed

	private void menuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClientesActionPerformed
		FrameCadastroCliente cadastroClientes = new FrameCadastroCliente(this);
		cadastroClientes.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuCadastroClientesActionPerformed

	private void menuCadastroItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroItensActionPerformed
		FrameCadastroItens cadastroItens = new FrameCadastroItens(this);
	    cadastroItens.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuCadastroItensActionPerformed

	private void menuIniciarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarCompraActionPerformed
		FrameMovimentoPreCompra compra = new FrameMovimentoPreCompra(this);
		compra.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuIniciarCompraActionPerformed

	private void menuIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarVendaActionPerformed
		FrameMovimentoPrePedido movimentoPedido = new FrameMovimentoPrePedido(this);
		movimentoPedido.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuIniciarVendaActionPerformed

	private void menuRemoverUsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoverUsuáriosActionPerformed
		RemoveUsuarios remove = new RemoveUsuarios(this);
		remove.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuRemoverUsuáriosActionPerformed

	private void menuAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarSenhaActionPerformed
		AlteraSenha altera = new AlteraSenha(this);
		altera.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_menuAlterarSenhaActionPerformed

	private void menuCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		FrameCadastroUsuario cadastroUsuario = new FrameCadastroUsuario(this);
		cadastroUsuario.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_jMenuItem1ActionPerformed

	@SuppressWarnings("unused")
	private void limpaCampos() {
		campoNome.setText("");
		campoSenha.setText("");
	}
	
	private void mensagem(String mensagem) {
		JOptionPane.showConfirmDialog(null,mensagem,"Mensagem",JOptionPane.CLOSED_OPTION);
	}
	
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JMenuItem menuAlterarSenha;
    private javax.swing.JMenuItem menuCadastroClientes;
    private javax.swing.JMenuItem menuCadastroFornecedores;
    private javax.swing.JMenuItem menuCadastroItens;
    private javax.swing.JMenuItem menuCadastroUsuarios;
    private javax.swing.JMenuItem menuConsultaClientes;
    private javax.swing.JMenuItem menuConsultaFornecedor;
    private javax.swing.JMenuItem menuConsultaItens;
    private javax.swing.JMenuItem menuIniciarCompra;
    private javax.swing.JMenuItem menuIniciarVenda;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuRemoverUsuários;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JPanel painelLogin;
    // End of variables declaration//GEN-END:variables

}
