/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameMovimentoPreCompra.java
 *
 * Created on 21/11/2010, 21:03:59
 */

package gui;

import javax.swing.JOptionPane;
import persistencia.PersistenciaFornecedor;
import pessoas.Fornecedor;
import estoque.Compra;
import interfaces.Communication;


/**
 *
 * @author isac
 */
public class FrameMovimentoPreCompra extends javax.swing.JFrame implements Communication{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Compra compra;
	/** Creates new form FrameMovimentoPreCompra */
    public FrameMovimentoPreCompra(Principal principal) {
        initComponents();
		this.principal=principal;
		this.compra = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preCompraCampoCnpj = new javax.swing.JTextField();
        preCompraLabelCabecalho = new javax.swing.JLabel();
        PreCompraLabelCnpj = new javax.swing.JLabel();
        preCompraBotaoPesquisar = new javax.swing.JButton();
        PreCompraBotaoOK = new javax.swing.JButton();
        preCompraBotaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        preCompraLabelCabecalho.setText("Insira o Cnpj do fornecedor que irá realizar a compra");

        PreCompraLabelCnpj.setText("Cnpj:");

        preCompraBotaoPesquisar.setText("Pesquisar");
        preCompraBotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preCompraBotaoPesquisarActionPerformed(evt);
            }
        });

        PreCompraBotaoOK.setText("Ok");
        PreCompraBotaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreCompraBotaoOKActionPerformed(evt);
            }
        });

        preCompraBotaoCancelar.setText("Cancelar");
        preCompraBotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preCompraBotaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PreCompraLabelCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preCompraCampoCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(PreCompraBotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preCompraBotaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preCompraBotaoPesquisar)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preCompraLabelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(preCompraLabelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreCompraLabelCnpj)
                    .addComponent(preCompraCampoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preCompraBotaoPesquisar)
                    .addComponent(PreCompraBotaoOK)
                    .addComponent(preCompraBotaoCancelar))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	/**
	 * 
	 * @param evt
	 */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.principal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.principal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing
    
	private void preCompraBotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preCompraBotaoCancelarActionPerformed
		principal.setEnabled(true);
		this.dispose();
	}//GEN-LAST:event_preCompraBotaoCancelarActionPerformed

	private void PreCompraBotaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreCompraBotaoOKActionPerformed
		if (preCompraCampoCnpj.getText() == null || preCompraCampoCnpj.getText().length() == 0){
			JOptionPane.showConfirmDialog(null,"O campo cnpj nao pode ser vazio","mensagem",JOptionPane.CLOSED_OPTION);
		}
		else{
			if (compra == null ){
				Fornecedor fornecedor = PersistenciaFornecedor.getInstance().searchFornecedor(preCompraCampoCnpj.getText());
				if (fornecedor == null ){
					JOptionPane.showConfirmDialog(null,"cnpj invalido","mensagem",JOptionPane.CLOSED_OPTION);
					preCompraCampoCnpj.setText("");
					return;
				}
				else{
					compra = new Compra(fornecedor);
				}
			}
			FrameMovimentoCompra movCompra = new FrameMovimentoCompra(principal,compra);
			movCompra.setVisible(true);
			this.dispose();
		}
	}//GEN-LAST:event_PreCompraBotaoOKActionPerformed

	private void preCompraBotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preCompraBotaoPesquisarActionPerformed
		ConsultaFornecedor consultaforecedor = new ConsultaFornecedor(this);
		consultaforecedor.setVisible(true);
		this.setEnabled(false);
	}//GEN-LAST:event_preCompraBotaoPesquisarActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameMovimentoPreCompra().setVisible(true);
//            }
//        });
//    }
	private Principal principal;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PreCompraBotaoOK;
    private javax.swing.JLabel PreCompraLabelCnpj;
    private javax.swing.JButton preCompraBotaoCancelar;
    private javax.swing.JButton preCompraBotaoPesquisar;
    private javax.swing.JTextField preCompraCampoCnpj;
    private javax.swing.JLabel preCompraLabelCabecalho;
    // End of variables declaration//GEN-END:variables
	@Override
	public void enviar() {
	
	}

	@Override
	public void receber(Object o) {
		if (o instanceof Fornecedor && o != null){
			compra = new Compra((Fornecedor)o);
			preCompraCampoCnpj.setText(((Fornecedor)o).getCnpj());
		}
		else {
			JOptionPane.showConfirmDialog(null,"Fornecedor invalido","mensagem",JOptionPane.CLOSED_OPTION);
		}
		
	}

}
