package gui;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import persistencia.PersistenciaEstoque;

import estoque.*;
import gui.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameMovimentoPedido.java
 *
 * Created on 12/11/2010, 01:14:38
 */

/**
 *
 * @author amanda
 */
public class FrameMovimentoPedido extends javax.swing.JFrame {
	private Principal principal;
	private Pedido pedido;
    
	/** Creates new form FrameMovimentoPedido */
    public FrameMovimentoPedido(Principal principal,Pedido pedido) {
        initComponents();
		this.principal = principal;
		if(pedido == null ){
			mensagem("OOps");
		}
		this.pedido = pedido;
		this.labelClienteValor.setText(pedido.getNomeCliente());
		this.labelDataValor.setText(pedido.getDataPedido(null));
    }

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FrameMovimentoPedidoLabelCodigo = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        FrameMovimentoPedidoLabelQuantidadeTotal = new javax.swing.JLabel();
        FrameMovimentoPedidoLabelPrecoTotal = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        labelClienteValor = new javax.swing.JLabel();
        labelQuantidadeValor = new javax.swing.JLabel();
        labelPrecoValor = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        campoCodigo = new javax.swing.JTextField();
        campoQuantidade = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoFinalizar = new javax.swing.JButton();
        labelCliente1 = new javax.swing.JLabel();
        labelDataValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        FrameMovimentoPedidoLabelCodigo.setText("Código:");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        FrameMovimentoPedidoLabelQuantidadeTotal.setText("Adicionar ou Editar");

        FrameMovimentoPedidoLabelPrecoTotal.setText("Quantidade:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labelCliente.setText("Cliente:");

        labelQuantidade.setText("Quantidade total:");

        labelPreco.setText("Preço total: R$");

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        campoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidadeActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar Alteração");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoFinalizar.setText("Finalizar Pedido");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        labelCliente1.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemover)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(FrameMovimentoPedidoLabelQuantidadeTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(FrameMovimentoPedidoLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPrecoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelQuantidadeValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDataValor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelClienteValor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(FrameMovimentoPedidoLabelPrecoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelClienteValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDataValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCliente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelQuantidade)
                            .addComponent(labelQuantidadeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPreco)
                            .addComponent(labelPrecoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FrameMovimentoPedidoLabelQuantidadeTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FrameMovimentoPedidoLabelCodigo)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrameMovimentoPedidoLabelPrecoTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botaoRemover)
                                    .addComponent(botaoEditar)
                                    .addComponent(botaoSalvar)
                                    .addComponent(botaoAdicionar)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoFinalizar)
                            .addComponent(botaoLimpar)
                            .addComponent(botaoSair))
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
		this.principal.setEnabled(true);
		this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
    	adicionar();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

	private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
		limpaCampos();
	}//GEN-LAST:event_botaoLimparActionPerformed

	private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
	}//GEN-LAST:event_campoCodigoActionPerformed

	private void campoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeActionPerformed
	}//GEN-LAST:event_campoQuantidadeActionPerformed

	private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
		int selecionado = jTable1.getSelectedRow();
		if(selecionado >= 0) {
			pedido.delItem(selecionado);
			jTable1.setModel(getData());
			}
		else{
			mensagem("nenhuma linha selecionada");
			return;
		}
	}//GEN-LAST:event_botaoRemoverActionPerformed

	private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
		int selecionado = jTable1.getSelectedRow();
		if(selecionado >= 0) {
			campoCodigo.setText(((Integer)pedido.overview().get(selecionado).getCodigoItem()).toString());
			campoCodigo.setEditable(false);
			campoQuantidade.setText(((Integer)pedido.overview().get(selecionado).getQuant()).toString());
			pedido.delItem(selecionado);
			jTable1.setModel(getData());
			}
		else{
			mensagem("nenhuma linha selecionada");
			return;
		}
	}//GEN-LAST:event_botaoEditarActionPerformed

	private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
		adicionar();
		campoCodigo.setEditable(true);
	}//GEN-LAST:event_botaoSalvarActionPerformed

	private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
		if(PersistenciaEstoque.getInstance().finalizarPedido(pedido)){
			mensagem("Pedido Finalizado Com sucesso!!");
			this.dispose();
		}
		else{
			mensagem("Não existem itens no pedido");
		}
	}//GEN-LAST:event_botaoFinalizarActionPerformed

	private void adicionar() {
		Integer codigo = 0,quant = 0;
		String nome;
		Item item = null;
		
		if(campoCodigo.getText() == null || campoCodigo.getText().length() == 0){
			mensagem("O campo Código não pode estar em branco");
			return;
		}
		else{
			try{
				codigo = Integer.parseInt(campoCodigo.getText());
				item = PersistenciaEstoque.getInstance().searchItem(codigo);
			}
			catch (NumberFormatException e) {
				nome = campoCodigo.getText();
				item = PersistenciaEstoque.getInstance().searchItem(nome);
			}
		}

		if(campoQuantidade.getText() == null || campoQuantidade.getText().length() == 0){
			mensagem("O campo Quantidade não pode estar em branco");
			return;
		}
		else{
			try{
				quant = Integer.parseInt(campoQuantidade.getText());
				if(quant <= 0 ){
					mensagem("Quantidade deve ser maior que zero");
					return;
				}
			}
			catch (NumberFormatException e) {
				mensagem("O campo quantidade não é um valor válido");
				return;
			}
		}
		
		if (item == null ){
			mensagem("Item não encontrado");
			return;
		}
		else{
			if(quant > item.getQuant()){
				mensagem("Quantidade de itens não disponível");
				return;
			}
			if(pedido.addItem(item,quant)){
				jTable1.setModel(getData());
				limpaCampos();
			}
			else{
				mensagem("oops!nao adicionei");
			}
		}
	}
	
	private TableModel getData(){
		ArrayList<ItemPedido> itens = pedido.overview();
		Vector<Vector<String>> dados = new Vector<Vector<String>>();
		Vector<String> headers = new Vector<String>();
		String [] headersName = new String[]{"Linha","Código","Nome","Preco","Quant","Subtotal"};
		int linha=0;
		Float total = (float) 0.0,subtotal = (float) 0.0;
		for (int i = 0; i < headersName.length; i++) {
			headers.add(headersName[i]);
		}
		if (itens != null){
			for (ItemPedido itensP : itens) {
		    	subtotal = itensP.getPrecoPedido() * itensP.getQuant();
				Vector<String> vetor = new Vector<String>();
				vetor.add(((Integer)linha).toString());
				vetor.add(((Integer)itensP.getCodigoItem()).toString());
				vetor.add(itensP.getNomeItem());
				vetor.add(((Float)itensP.getPrecoPedido()).toString());
				vetor.add(((Integer)itensP.getQuant()).toString());
				vetor.add(subtotal.toString());
				total+=subtotal;
				dados.add(linha,vetor);
				linha++;
			}
		}
		else{
			DefaultTableModel model = new DefaultTableModel(new String[][]{}, headersName);
			labelPrecoValor.setText("0.00");
			labelQuantidadeValor.setText("0");
			return model;			
		}
		DefaultTableModel model = new DefaultTableModel(dados, headers);
		labelPrecoValor.setText(total.toString());
		labelQuantidadeValor.setText(((Integer)dados.size()).toString());
		return model;
 	}

	private void limpaCampos() {
		campoCodigo.setText("");
		campoQuantidade.setText("");
	}
	
	private void mensagem(String mensagem) {
		JOptionPane.showConfirmDialog(null,mensagem,"Mensagem",JOptionPane.CLOSED_OPTION);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameMovimentoPedidoLabelCodigo;
    private javax.swing.JLabel FrameMovimentoPedidoLabelPrecoTotal;
    private javax.swing.JLabel FrameMovimentoPedidoLabelQuantidadeTotal;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelCliente1;
    private javax.swing.JLabel labelClienteValor;
    private javax.swing.JLabel labelDataValor;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelPrecoValor;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelQuantidadeValor;
    // End of variables declaration//GEN-END:variables

}
